### ISSUE TITLE
BgOpacity on Partylist

### ISSUE THREAD

**Issue by agjevik999** [bangplaysgames/GlamourUI#10]
I'm been messing around trying to make the partylist transparent, but I've been unable to fix it. I've edited .lua file in the BgOpacity slot, but it doesn't affect anything in game after reloading. Am I doing something wrong here? I've also tried editing the settings.lua in my saved layout folder but no change there either.

**Comment by bangplaysgames** [comment]
The BgOpacity setting is specifically for the unthemed party list.  For the themed party list, there is a background texture file in the theme folder.  If you want a transparent background, just make that file totally transparent.  (I recommend making a copy of the theme folder for any changes)
