### ISSUE TITLE
Pet Tp

### ISSUE THREAD

**Issue by Thedog888** [bangplaysgames/GlamourUI#2]
![Screenshot (75)](https://user-images.githubusercontent.com/84095598/210935338-ddec690e-cca2-450c-affd-58cdfd0d1cdd.png)

The tp of the familiar goes way past were the tp is suppose to be maxed out at on the bar. In the picture you can see my tp ends where its suppose to but the familiar's tp doesn't.

**Comment by bangplaysgames** [comment]
This was an oversight on my part with the new layout engine.  I'll have this fixed in the next release.

**Comment by bangplaysgames** [comment]
This should be resolved in 0.4.0
