### ISSUE TITLE
Target Bar

### ISSUE THREAD

**Issue by Thedog888** [bangplaysgames/GlamourUI#3]
When trying to change the Target Bar in the config it will not change the size and pop back to whatever it is at default.

**Comment by bangplaysgames** [comment]
You're adjusting the target bar gui_scale setting?

**Comment by Thedog888** [comment]
yes and it will not change.

**Comment by bangplaysgames** [comment]
I'm currently looking into this.  For now,  the command works to set the scale:

/glam targetbar setscale #

**Comment by bangplaysgames** [comment]
Fixed in 0.4.1
