### ISSUE TITLE
Status Icons for Party list and Target Bar

### ISSUE THREAD

**Issue by Nullsloth** [bangplaysgames/GlamourUI#4]
Monster debuff icons for targetbar and player buff icons on party members and self.

**Comment by bangplaysgames** [comment]
Status icons on the party list is intended for the future.

Target status icons, I'm not sure if this is possible or not.  If it is, I will consider adding it around the same time as the party status icons.

**Comment by bangplaysgames** [comment]
Implemented with 1.0.

Status icons are not implemented for target and I currently have no plans to do so due to no graceful way to accomplish this.
