### ISSUE TITLE
Pet Info

### ISSUE THREAD

**Issue by Thedog888** [bangplaysgames/GlamourUI#5]
Is there a way that you could display the charges (for abilities) of the pet next to the pet bar.

**Comment by bangplaysgames** [comment]
I will look into this.  I'm not sure how to go about it, atm, so it might take a bit,  but I'll do my best to get it implemented.

**Comment by bangplaysgames** [comment]
With the recent changes Horizon has made to the recast of Ready,  I'm going to currently mark this as not intended.  I may revisit it in the future, but for now, I wouldn't plan on it.
