### ISSUE TITLE
Full party list

### ISSUE THREAD

**Issue by Thedog888** [bangplaysgames/GlamourUI#6]
![Screenshot (76)](https://user-images.githubusercontent.com/84095598/211129486-1beaaea9-0c7b-4f17-8ef1-8f138081c820.png)
The bars don't seem to be lining up correctly I tried making the padding more doesn't seem to work. the padding only seems to space the first one and second one apart. While the 2nd through 6 are all stuck to one another.

**Comment by Thedog888** [comment]
![Screenshot (77)](https://user-images.githubusercontent.com/84095598/211141152-0aab722d-e38b-43ed-a930-0e2c0700c456.png)
it also does it with the pet

**Comment by bangplaysgames** [comment]
Try adjusting the padding setting in layout.  If you're not on the latest version, please update to that.

**Comment by Thedog888** [comment]
This seems to be resolved since the update
