### ISSUE TITLE
subtarget bar request

### ISSUE THREAD

**Issue by timaruxi** [bangplaysgames/GlamourUI#8]
Hello!  Can subtarget bar be added?  Its the bar that would show a secondary target while locked onto primary target.

![image](https://user-images.githubusercontent.com/122398598/211642311-c1f7d310-25e5-4bca-8696-7cbda438c6dc.png)

**Comment by bangplaysgames** [comment]
I'll do my best to have something implemented for the next version update.

**Comment by bangplaysgames** [comment]
Implemented with version 0.7.0
